import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { configureAbly, useChannel } from '@ably-labs/react-hooks';

type Props = {
  ablyAPI: string;
};

const Home: NextPage<Props> = () => {
  const [count, setCount] = useState([1]);
  const [messages1, updateMessages1] = useState<any>([]);
  const [messages2, updateMessages2] = useState<any>([]);
  const [messages3, updateMessages3] = useState<any>([]);

  configureAbly({
    authUrl: 'api/createTokenRequest',
  });

  const [channel1] = useChannel('channel1', (message1) => {
    updateMessages1((prev: []) => [...prev, message1]);
  });

  const [channel2] = useChannel('channel2', (message2) => {
    updateMessages2((prev: []) => [...prev, message2]);
  });

  const [channel3] = useChannel('channel1', (message3) => {
    updateMessages3((prev: []) => [...prev, message3]);
  });

  const clickHandler = () => {
    setCount([...count, count[count.length - 1] + 1]);
  };

  const send1 = () => {
    channel1.publish('sending Messages', { text: 'message text' });
  };

  const send2 = () => {
    channel2.publish('test-message', { text: 'message text' });
  };

  const send3 = () => {
    channel3.publish('test-message', { text: 'message text' });
  };

  console.log('msgs 1', messages1);
  console.log('msgs 2', messages2);
  console.log('msgs 3', messages3);
  /**
   * Test code
   */

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <button onClick={clickHandler}>Click me</button>
        <button onClick={send1}>Send1</button>
        <button onClick={send2}>Send2</button>
        <button onClick={send3}>Send3</button>

        {count.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </div>
    </div>
  );
};

export default Home;
